### ISSUE TITLE
Provide warning on COBRA health insurance

### ISSUE THREAD

**Issue by porkcharsui** [derwiki/layoff-runbook#5]
COBRA benefits do not work in situations when a company goes under. 

The insurance company will gladly take your premium check but not tell you that you have no health insurance under COBRA when an employer no longer exists to pay employee insurance premiums.

**Comment by derwiki** [comment]
Thank you! Updated in https://github.com/derwiki/layoff-runbook/commit/bf12d51c7fb9026e505870614abce300cfd250bb
